### ISSUE TITLE
Unable to lookup chisel... (build 41)

### ISSUE THREAD

**Issue by Maokuma** [TheCricket/Chisel-2#197]
Hi, I have an dedicated server with chisel 2 build 41, and connected clients report on crash:
(Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.block.BlockMarbleWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?)
Long version Forge log: http://pastebin.com/rjdWEAeh

The crash error appears at random when the world is generating. Removing Chisel 2 solves the error after a crash. Only clients crashes when running of an dedicated server so the log is from the client only, server gives no error at all involving Chisel 2 when generating new area, except the kicking player for reasons part.

I have been encountering this error for 2 weeks now and tested a lot of stuff to get it to work. It was most stable when removing the mod "Fantastic Fish" (odd).

Sometimes, the server has an absurd tickrate and gives when entering water: (java.lang.ArrayIndexOutOfBoundsException: -1) with about the same log, except reconnecting to server works.

**Comment by tterrag1098** [comment]
Nothing in that crash log mentions chisel...

**Comment by Maokuma** [comment]
The ( Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.block.BlockMarbleWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?) is always triggered when the crash happens.
And removing chisel 2 makes me able to log into the game. So I thought it could be an odd conflict due to the weird AI error in the report.
Thanks! And I'm sorry if I'm wrong.

**Comment by tterrag1098** [comment]
Yes that is a mistake on our part but it will not cause a crash

**Comment by TheCricket** [comment]
If it says is something wrong with the registry that's forge trying to use something we haven't implemented

**Comment by Maokuma** [comment]
Thanks for an awesome mod. And thanks for the help.

**Comment by krisavi** [comment]
I think it is somehow connected to issue serendipitymc has on one of the servers.

That is probably the most useful part of the crash report you need:

23:18:07] [Client thread/INFO] [STDOUT/]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 2/2/15 11:18 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.cricketcraft.chisel.client.render.RenderBlocksColumn.connected(RenderBlocksColumn.java:19)
	at com.cricketcraft.chisel.client.render.RenderBlocksColumn.func_147784_q(RenderBlocksColumn.java:72)
	at com.cricketcraft.chisel.client.render.BlockAdvancedMarbleRenderer.renderWorldBlock(BlockAdvancedMarbleRenderer.java:70)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
	at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1553)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.cricketcraft.chisel.client.render.RenderBlocksColumn.connected(RenderBlocksColumn.java:19)
	at com.cricketcraft.chisel.client.render.RenderBlocksColumn.func_147784_q(RenderBlocksColumn.java:72)
	at com.cricketcraft.chisel.client.render.BlockAdvancedMarbleRenderer.renderWorldBlock(BlockAdvancedMarbleRenderer.java:70)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
	at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1553)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['mercor'/77555, l='MpServer', x=-1108.85, y=68.62, z=110.28]]
	Chunk stats: MultiplayerChunkCache: 25, 25
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1464,64,1543), Chunk: (at 8,4,7 in -92,96; contains blocks -1472,0,1536 to -1457,255,1551), Region: (-3,3; contains chunks -96,96 to -65,127, blocks -1536,0,1536 to -1025,255,2047)
	Level time: 83664141 game time, 22382506 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 8 total; [EntitySpark['Spark'/77771, l='MpServer', x=-1109.50, y=68.50, z=79.50], EntityVillager['Villager'/77773, l='MpServer', x=-1123.78, y=5.00, z=131.34], EntityBroom['Enchanted Broom'/77775, l='MpServer', x=-1133.31, y=69.25, z=133.53], EntityClientPlayerMP['mercor'/77555, l='MpServer', x=-1108.85, y=68.62, z=110.28], EntityImp['Hilopael Tramater'/77774, l='MpServer', x=-1125.22, y=63.00, z=129.78], EntityBat['Bat'/77777, l='MpServer', x=-1086.31, y=27.10, z=82.25], EntityCreeper['Creeper'/77776, l='MpServer', x=-1136.41, y=29.00, z=124.94], EntityZombie['Zombie'/77778, l='MpServer', x=-1081.84, y=51.00, z=128.56]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"cf722de":1037) <- cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --

**Comment by tterrag1098** [comment]
Not quite @TheCricket, it means the name in ChiselBlocks doesn't match up with the registry name of any block so it prints an error.

**Comment by cocopuffs99** [comment]
I'm getting the same error and crash CTD
