### ISSUE TITLE
Deobj jar contains duplicate classes making it unusable

### ISSUE THREAD

**Issue by bdew** [TheCricket/Chisel-2#256]
This makes the FML crash when using it in a dev environment

    java.lang.IllegalArgumentException: Multiple entries with same key: chisel=FMLMod:chisel{2.3.7.34} and chisel=FMLMod:chisel{2.3.7.34}
      at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150)
      at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104)
      at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70)
      at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254)
      at com.google.common.collect.Maps.uniqueIndex(Maps.java:1166)
      at com.google.common.collect.Maps.uniqueIndex(Maps.java:1140)
      at cpw.mods.fml.common.Loader.identifyMods(Loader.java:349)
      at cpw.mods.fml.common.Loader.loadMods(Loader.java:468)
      at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
      at net.minecraft.client.Minecraft.startGame(Minecraft.java:480)
      at net.minecraft.client.Minecraft.run(Minecraft.java:867)
      at net.minecraft.client.main.Main.main(SourceFile:148)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:606)
      at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
      at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
      at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:85)
      at GradleStart.main(GradleStart.java:45)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:606)
      at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

This happens becaue of this hack (that you added for IDEA i guess?):

> sourceSets { main { output.resourcesDir = output.classesDir } }

You can fix it by either adding

>  duplicatesStrategy "exclude"

Or changing the from line to "sourceSets.main.output.classesDir" in task deobfJar

**Comment by tterrag1098** [comment]
This has been fixed in the latest deobf jars

**Comment by bdew** [comment]
Oh derp i was looking at master, i see that that output.resourcesDir = output.classesDir  hack was removed on dev.
