### ISSUE TITLE
Crash when opening Inventory - BlockMarblePillarRenderer.renderInventoryBlock

### ISSUE THREAD

**Issue by CptSpaceToaster** [TheCricket/Chisel-2#277]
**I Haven't checked to see if this was a duplicate or not.**

This is in the Material Energy^4 modpack.

```
---- Minecraft Crash Report ----
// You're mean.
Time: 3/26/15 5:55 PM
Description: Rendering item
java.lang.IndexOutOfBoundsException: Index: 8, Size: 7
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at com.cricketcraft.chisel.block.BlockCarvablePillar.getCtmIcon(BlockCarvablePillar.java:34)
at com.cricketcraft.chisel.client.render.BlockMarblePillarRenderer.renderInventoryBlock(BlockMarblePillarRenderer.java:31)
at cpw.mods.fml.client.registry.RenderingRegistry.renderInventoryBlock(RenderingRegistry.java:125)
at net.minecraft.src.FMLRenderAccessLibrary.renderInventoryBlock(FMLRenderAccessLibrary.java:59)
at net.minecraft.client.renderer.RenderBlocks.func_147800_a(RenderBlocks.java:8145)
at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:446)
at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:488)
at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:268)
at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)
at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by warlordjones** [comment]
That's down to me changing the way ice pillars worked, and reordering the meta, but I thought I had a safety net in place to prevent this crash...

**Comment by hossumquat** [comment]
This is my crash report.  It's preventing me from playing ME4 at all, which is problematic since I'm recording a series with it on Youtube.  Is there a simple solution I can use to get my world to load again?  Thanks.

**Comment by TheCricket** [comment]
Did you update chisel manually?

**Comment by hossumquat** [comment]
Yes, I removed chisel2_DEV-2.2.2.b8eaaca.jar from the mods directory and put chisel2-2.3.9.36.jar instead.  Still crashes when I open my inventory:

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 4/1/15 9:38 PM
Description: Rendering item

java.lang.IndexOutOfBoundsException: Index: 8, Size: 7
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.cricketcraft.chisel.block.BlockCarvablePillar.getCtmIcon(BlockCarvablePillar.java:34)
	at com.cricketcraft.chisel.client.render.BlockMarblePillarRenderer.renderInventoryBlock(BlockMarblePillarRenderer.java:31)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderInventoryBlock(RenderingRegistry.java:125)
	at net.minecraft.src.FMLRenderAccessLibrary.renderInventoryBlock(FMLRenderAccessLibrary.java:59)
	at net.minecraft.client.renderer.RenderBlocks.func_147800_a(RenderBlocks.java:8145)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:446)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:488)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:268)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by TheCricket** [comment]
Use the version the pack was made to have

**Comment by hossumquat** [comment]
Ok, then refer to the original crash report from the 26th as that was using the one that the modpack includes (chisel2_DEV-2.2.2.b8eaaca.jar).  Modpack has not been updated since then.
