### ISSUE TITLE
Crash with AutoChisel

### ISSUE THREAD

**Issue by Namikon** [TheCricket/Chisel-2#417]
Sorry for the confusing post-delete-post thing...

We just got the same problem as in Chisel-2/Chisel-2#392 with the latest chisel version: (2.5.1.44)
http://pastebin.com/N5T6rJF1

The player said that he placed the Autochisel, opened the GUI and tried to place in a pattern. The AutoChisel didn't want to accept it, and then his client and the server crashed with the log above

Edit: I even had to remove the block via MCEdit, since the server entered a crash-loop

**Comment by Zaflis** [comment]
Same here, server not starting now.

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at com.cricketcraft.chisel.block.tileentity.TileEntityAutoChisel.getTarget(TileEntityAutoChisel.java:184)
at com.cricketcraft.chisel.block.tileentity.TileEntityAutoChisel.func_145845_h(TileEntityAutoChisel.java:116)
at net.minecraft.world.World.func_72939_s(World.java:1939)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by TheCricket** [comment]
Just disable the block in the config for now, It will be getting fixed soon. I have midterms

**Comment by timfennis** [comment]
I'm having the same issue. I used an auto chisel with all upgrades to revert ztone blocks back to their original form. It seem to break if the ztone block isn't in it's `:0` form

**Comment by TehNut** [comment]
@timfennis This sounds more like you don't have the ChiselTones config set how you want.

**Comment by timfennis** [comment]
Well it crashed my server to a point where we can't start it anymore so surely it's more then a config issue?
