### ISSUE TITLE
Crash with vanilla/hub servers

### ISSUE THREAD

**Issue by LemADEC** [TheCricket/Chisel-2#425]
When connecting to a vanilla server (typically used as hub on a network), client will crash and the following logs are seen in console:

```
[23:26:37] [Client thread/INFO]: [CHAT] You have no new mail.
[23:26:37] [Client thread/INFO] [FML]: Applying holder lookups
[23:26:37] [Client thread/WARN] [FML]: Unable to lookup chisel:cobblestoneWall for public static team.chisel.block.BlockCarvableWall team.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?
[23:26:37] [Client thread/WARN] [FML]: Unable to lookup chisel:obsidian2 for public static team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.obsidian2. Is there something wrong with the registry?
[23:26:37] [Client thread/WARN] [FML]: Unable to lookup chisel:voidstonerunic for public static team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.voidstonerunic. Is there something wrong with the registry?
[23:26:37] [Client thread/WARN] [FML]: Unable to lookup chisel:circuits for public static team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.circuits. Is there something wrong with the registry?
[23:26:37] [Client thread/INFO] [FML]: Holder lookups applied
[23:26:39] [Client thread/INFO] [MapWriter]: Mw.close: closing...
[23:26:39] [Client thread/INFO] [MapWriter]: waiting for 194 tasks to finish...
[23:26:40] [Client thread/INFO] [MapWriter]: done
```

This is observed with Chisel2 2.9.2.8 as part of FTB Infinity 2.0.0

**Comment by Drullkus** [comment]
This is not the issue. Give us the whole log.

**Comment by LemADEC** [comment]
That's the only thing showing up client side, with a bit of variations.

I think issue is more on server side actually:
```
[18:45:56 INFO]: LemADEC[/xxx.xxx.xxx.xxx:49556] logged in with entity id 59 at ([Gateway] -128.5, 84.0, 217.5)
[18:45:56 WARN]: Failed to handle packet for /xxx.xxx.xxx.xxx:49556
java.lang.IllegalStateException: Too many channels registered
>       at com.google.common.base.Preconditions.checkState(Preconditions.java:145) ~[spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
>       at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.addChannel(CraftPlayer.java:1068) ~[spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
>       at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1956) ~[spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
>       at net.minecraft.server.v1_7_R4.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:39) ~[spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
>       at net.minecraft.server.v1_7_R4.PacketPlayInCustomPayload.handle(PacketPlayInCustomPayload.java:51) ~[spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
>       at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) ~[spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
>       at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
>       at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
>       at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
>       at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
>       at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
>       at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
[18:45:56 INFO]: LemADEC lost connection: Internal server error
```
so probably not much to do with Chisel.

**Comment by Drullkus** [comment]
Forge-bukkit fusions. :\

We're not fixing this one.

**Comment by LemADEC** [comment]
Not a Chisel issue, closing
