### ISSUE TITLE
Render Chisel Snowman

### ISSUE THREAD

**Issue by voidswrath** [TheCricket/Chisel-2#443]
Yeah not sure what is going on here on my client. My client log had this and my cauldron server timed out

[13:48:20] [Client thread/ERROR]: Couldn't render entity
java.lang.NullPointerException
    at com.cricketcraft.chisel.client.render.RenderChiselSnowman.renderEquippedItems(RenderChiselSnowman.java:48) ~[RenderChiselSnowman.class:?]
    at com.cricketcraft.chisel.client.render.RenderChiselSnowman.func_77029_c(RenderChiselSnowman.java:32) ~[RenderChiselSnowman.class:?]
    at net.minecraft.client.renderer.entity.NPCRendererHelper.renderEquippedItems(NPCRendererHelper.java:39) ~[NPCRendererHelper.class:?]
    at noppes.npcs.client.renderer.RenderCustomNpc.func_77029_c(RenderCustomNpc.java:69) ~[RenderCustomNpc.class:?]
    at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:213) [boh.class:?]
    at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:23) [bok.class:?]
    at noppes.npcs.client.renderer.RenderNPCInterface.func_76986_a(RenderNPCInterface.java:233) [RenderNPCInterface.class:?]
    at noppes.npcs.client.renderer.RenderNPCHumanMale.renderPlayer(RenderNPCHumanMale.java:133) [RenderNPCHumanMale.class:?]
    at noppes.npcs.client.renderer.RenderCustomNpc.renderPlayer(RenderCustomNpc.java:62) [RenderCustomNpc.class:?]
    at noppes.npcs.client.renderer.RenderNPCHumanMale.func_76986_a(RenderNPCHumanMale.java:411) [RenderNPCHumanMale.class:?]
    at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293) [bnn.class:?]
    at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:271) [bnn.class:?]
    at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:244) [bnn.class:?]
    at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:471) [bma.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224) [blt.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015) [blt.class:?]
    at sushen.aeiao.func_78480_b(Unknown Source) [aeiao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]

**Comment by voidswrath** [comment]
Had PVZ mod installed but not on server so the entity was just freaking out client side
